### PR TITLE
Adds Mechoid's P.T.S.D. borg sprite-set.

### PR DESCRIPTION
**Pull request by Mechoid**
Adds Mechoid's P.T.S.D. borg sprite set, and the appropriate config.

### CODE REVIEW

**Comment by Anewbe** [comment]
https://forum.ss13polaris.com/viewtopic.php?f=20&p=109

**Comment by Mechoid** [comment]
I should not make PR's when I'm in headache mode, as I forget things.

**Comment by Anewbe** [comment]
Let me know when this is fixed, then?

**Comment by Mechoid** [comment]
@Anewbe The thing I forgot was the link to the forum post

**Pull request merged**
